Reorder steps to speed up the build

diff --git a/.github/workflows/build-test-bundle.yml b/.github/workflows/build-test-bundle.yml
--- a/.github/workflows/build-test-bundle.yml
+++ b/.github/workflows/build-test-bundle.yml
@@ -13,29 +13,15 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    name: Build, Test, and Bundle
     steps:
-      - name: Checkout the Repository
-        uses: actions/checkout@v2
-
       - name: Pull Docker Images
         run: >
           docker pull contextgarden/context:lmtx &
-          docker pull texlive/texlive:latest
+          docker pull texlive/texlive:latest &
 
-      - name: Test the package under TeXLive
-        run: >
-          docker run
-          -v "$GITHUB_WORKSPACE":/mnt
-          -e TEXMFHOME=/mnt/texmf
-          texlive/texlive:latest
-          /bin/sh -c '
-            mktexlsr &&
-            cd /mnt/tests/ &&
-            lualatex ./latex-basic.tex | grep === | diff -ws /mnt/tests/expected-results.txt - ||
-            { echo "::error::LaTeX Test Failed!"; exit 1; } &&
-            luatex ./plain-basic.tex | grep === | diff -ws /mnt/tests/expected-results.txt - ||
-            { echo "::error::Plain TeX Test Failed!"; exit 1; }
-          '
+      - name: Checkout the Repository
+        uses: actions/checkout@v2
 
       - name: Build Documentation
         run: >
@@ -51,6 +37,21 @@ jobs:
             { echo "::error::ConTeXt Test Failed!"; exit 1; } &&
             cd /mnt/docs;
             context lwc-documentation.tex
+          '
+
+      - name: Test the package under TeXLive
+        run: >
+          docker run
+          -v "$GITHUB_WORKSPACE":/mnt
+          -e TEXMFHOME=/mnt/texmf
+          texlive/texlive:latest
+          /bin/sh -c '
+            mktexlsr &&
+            cd /mnt/tests/ &&
+            lualatex ./latex-basic.tex | grep === | diff -ws /mnt/tests/expected-results.txt - ||
+            { echo "::error::LaTeX Test Failed!"; exit 1; } &&
+            luatex ./plain-basic.tex | grep === | diff -ws /mnt/tests/expected-results.txt - ||
+            { echo "::error::Plain TeX Test Failed!"; exit 1; }
           '
 
       - name: Bundle the package
